GENRES={
"adv_animal": "Природа и животные",
"adv_history": "Исторические приключения",
"adv_geo": "Путешествия и география",
"adv_indian": "Приключения про индейцев",
"adv_maritime": "Морские приключения",
"adv_modern": "Современные приключения",
"adv_western": "Вестерн",
"adventure": "Приключения",
"antique_ant": "Античная литература",
"antique_east": "Древневосточная литература",
"antique_european": "Европейская старинная литература",
"antique_myths": "Мифы. Легенды. Эпос",
"antique_russian": "Древнерусская литература",
"antique": "Старинная литература",
"biogr_leaders": "Биографии",
"child_4": "Детям до 4",
"child_adv": "Детские приключения",
"child_det": "Детские остросюжетные",
"child_education": "Детская образовательная литература",
"child_tale": "Сказка",
"child_prose": "Детская проза",
"child_verse": "Детские стихи",
"child_sf": "Детская фантастика",
"children": "Детская литература",
"comp_db": "Базы данных",
"comp_hard": "Компьютерное 'железо' (аппаратное обеспечение)",
"comp_osnet": "ОС и Сети",
"comp_programming": "Программирование",
"comp_soft": "Программы",
"comp_www": "Интернет",
"computers": "Компьтерная литература",
"det_action": "Боевик",
"det_classic": "Классический детектив",
"det_crime": "Криминальный детектив",
"det_espionage": "Шпионский детектив",
"det_hard": "Крутой детектив",
"det_history": "Исторический детектив",
"det_irony": "Иронический детектив",
"det_police": "Полицейский детектив",
"det_political": "Политический детектив",
"det_maniac": "Маньяки",
"detective": "Детектив",
"thriller": "Триллер",
"economics": "Экономика",
"fantasy_fight": "Боевое фэнтези",
"foreign_adventure": "Зарубежные приключения",
"foreign_antique": "Зарубежная старинная литература",
"foreign_children": "Зарубежные детские книги",
"foreign_contemporary": "Современная зарубежная литература",
"foreign_detective": "Зарубежные детективы",
"foreign_fantasy": "Зарубежное фэнтези",
"foreign_love": "Зарубежные любовные романы",
"foreign_prose": "Зарубежная классика",
"foreign_publicism": "Зарубежная публицистика",
"foreign_religion": "Зарубежная эзотерическая и религиозная литература",
"foreign_sf": "Зарубежная фантастика",
"historical_fantasy": "Историческое фэнтези",
"home_cooking": "Кулинария",
"home_pets": "Домашние животные",
"home_crafts": "Хобби и ремесла",
"home_entertain": "Развлечения",
"home_health": "Здоровье",
"home_garden": "Сад и огород",
"home_diy": "Сделай сам",
"home_sport": "Спорт",
"home_sex": "Эротика, Секс",
"home": "Домоводство",
"humor_anecdote": "Анекдоты",
"humor_prose": "Юмористическая проза",
"humor_verse": "Юмористические стихи",
"humor": "Юмор",
"literature": "Литература",
"literature_18": "Литература 18 века",
"literature_19": "Литература 19 века",
"literature_20": "Литература 20 века",
"literature_classics": "Классика",
"literature_adv": "Приключения",
"literature_drama": "Драма",
"literature_history": "История",
"literature_political": "Политика",
"literature_rus_classsic": "Русская классика",
"literature_short": "Короткие рассказы",
"literature_usa": "Американская литература",
"literature_western": "Вестерн",
"love_contemporary": "Современные любовные романы",
"love_detective": "Остросюжетные любовные романы",
"love_erotica": "Эротика ",
"love_hard": "Страстная эротика",
"love_history": "Исторические любовные романы",
"love_short": "Короткие любовные романы",
"love_sf": "Любовная фантастика",
"love": "Любовные романы",
"magician_book": "Магия, волшебство",
"dramaturgy": "Драматургия",
"poetry": "Поэзия",
"поэзия": "Поэзия",
"nonf_biography": "Биографии и Мемуары",
"nonf_criticism": "Критика",
"nonf_publicism": "Публицистика",
"design": "Искусство и Дизайн",
"nonfiction": "Документальная литература",
"nonfiction_politics": "Политическая история",
"other": "Разное",
"politics": "Политика",
"popadanec": "Попаданец",
"prose_classic": "Классическая проза",
"prose_contemporary": "Современная проза",
"prose_counter": "Контркультура",
"prose_history": "Историческая проза",
"prose_military": "Военная проза",
"prose_rus_classic": "Русская классическая проза",
"prose_su_classics": "Советская классическая проза",
"proce": "Проза",
"prose": "Проза",
"short_story": "Короткие расказы",
"ref_dict": "Словари",
"ref_encyc": "Энциклопедии",
"ref_guide": "Руководства",
"ref_ref": "Справочники",
"reference": "Справочная литература",
"religion_rel": "Религия",
"religion_esoterics": "Эзотерика",
"religion_orthodoxy": "Ортодоксальные учения",
"religion religion-self sci-religion": "Религия и наука",
"religion_self": "Самосовершенствование",
"religion": "Религиозная литература",
"romance": "Рыцарский роман",
"romance_fantasy": "Рыцарское фэнтези",
"romance_sf": "Рыцарская фантастика",
"russian_fantasy": "Русское фэнтези",
"sci_biology": "Биология",
"sci_business": "Деловая литература",
"sci_chem": "Химия",
"sci_culture": "Культурология",
"sci_geo": "География",
"sci_history": "История",
"sci_juris": "Юриспруденция",
"sci_linguistic": "Языкознание",
"sci_math": "Математика",
"sci_medicine": "Медицина",
"sci_psychology": "Психология",
"sci_philosophy": "Философия",
"sci_phys": "Физика",
"sci_politics": "Политика",
"sci_religion": "Религиоведение",
"sci_tech": "Технические науки",
"science": "Научная литература",
"sagas": "Сага",
"sf_action": "Боевая фантастика",
"sf_cyberpunk": "Киберпанк",
"sf_detective": "Детективная фантастика",
"sf_epic": "Эпическая фантастика",
"sf_etc": "Разная фантастика",
"sf_history": "Альтернативная история",
"sf_history_avant": "Историческая авантюра",
"sf_heroic": "Героическая фантастика",
"sf_horror": "Ужасы и Мистика",
"sf_humor": "Юмористическая фантастика",
"sf_fantasy": "Фэнтези",
"city_fantasy": "Городское фэнтези",
"sf_fantasy_city": "Городское фэнтези",
"sf_mystic": "Мистика",
"sf_space": "Космическая фантастика",
"sf_social": "Социально-психологическая фантастика",
"sf": "Научная Фантастика ",
"vampire_book": "Вампиры",
"screenplays": "Сценарии",
"visual_arts": "Изобразительные искусства",
"unrecognised": "Прочая"
}