SUBJ={
0:['Мой Город',0,0],
1:['Ю.Бутово (М)',0,0],
4:['Битцевский парк (М)',0,0],
7:['Крым',0,0],
8:['Доломитовые Альпы',0,0],
2:['Природа',0,0],
5:['Стереокартинки',0,0],
6:['Эротика (Анимэ)',0,0],
};
TITLES=[
[8,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/DOL-ALPINE-U-TIROL-2.jpg','Доломитовые Альпы. Южный Тироль. 1',0,0],
[8,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/DOL-ALPINE-U-TIROL.jpg','Доломитовые Альпы. Южный Тироль. 2',0,0],
[8,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/DOL-ALPINE-ITALIA.jpg','Доломитовые Альпы. Италия. 1',0,0],
[8,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/DOL-ALPINE-1.jpg','Доломитовые Альпы. Италия. 2',0,0],
[8,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/DOL-ALPINE-2.jpg','Доломитовые Альпы. Италия. 3',0,0],
[8,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/DOL-ALPINE-3.jpg','Доломитовые Альпы. Италия. 4',0,0],
[8,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/DOL-ALPINE-4.jpg','Доломитовые Альпы. Италия. 5',0,0],
[8,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/DOL-ALPINE-5.jpg','Доломитовые Альпы. Италия. 6',0,0],
[7,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/KRYM-LASTOCKINO-GNEZDO-1.jpg','Крым. Ялта. 1',0,0],
[7,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/KRYM-LASTOCKINO-GNEZDO-2.jpg','Крым. Ялта. 2',0,0],
[7,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/KRYM-LASTOCKINO-GNEZDO-3.jpg','Крым. Ялта. 3',0,0],
[7,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/KRYM-LASTOCKINO-GNEZDO-4.jpg','Крым. Ялта. 4',0,0],
[7,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/KRYM-LASTOCKINO-GNEZDO.jpg','Крым. Ялта. 5',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-ALLEY-V-OKTYBRE.jpg','Красивая аллея в октябре. Октябрь 2021г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-ALLEY-V-SERBINKE.jpg','Осенняя аллея в Щербинке. Октябрь 2021г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-DK-SERBINKA.jpg','ДК Щербинка. Октябрь 2020г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-DK-SERBINKA-2.jpg','ДК Щербинка. Октябрь 2020г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-EKSKAVATOR-U-SIMONOVA-MONASTYRY.jpg','Экскаватор у Симонова монастыря. Октябрь 2021г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-ELKA-SO-ZVEZDOI.jpg','Новогодняя елка со звездой. Январь 2021г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-KLUMBA-NA-VOSTOCNOI.jpg','Клумба на Восточной. Июль 2019г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-LENINSKAY-SLOBODA-VESNOI.jpg','Вид на Ленинскую слободу. Апрель 2018г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-NOVOGODNYY-ELKA.jpg','Новогодняя елка. Декабрь 2020г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-PANORAMA-ZAKATA-V-BUTOVO.jpg','Панорама заката в Бутово. Сентябрь 2020г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-PERESVETOV-PEREULOK-V-ZELTYK-LISTYK.jpg','Пересветов переулок в желтых листьях. Октябрь 2021г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-PUSTOI-PODZEMNYI-PEREKOD.jpg','Пустой подземный переход. Октябрь 2021г.',0,0],
[0,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/M-STADION-TORPEDO.jpg','Стадион Торпедо. Октябрь 2014г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-ALLEY-V-ZAKARINO.jpg','Аллея в Захарьино. Июль 2017г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-DOROGA-U-V-ZAKARINO.jpg','Улица в Захарьино осенью. Сентябрь 2019г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-DRUGOE-BOLOTTE-V-ZAKARINO.jpg','Болото в Захарьино. Сентябрь 2017г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-LUZAIKA-STRIZENNAY.jpg','Стриженая лужайка. Август 2020г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-MAISKII-ZAKAT-IZ-OKNA.jpg','Закат из окна. Май 2021г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-NOCNOE-BUTOVO.jpg','Ночное Бутово. Сентябрь 2020г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-NOCNOI-ZAVOD.jpg','Завод ЩЛЗ в сумерках. Ноябрь 2020г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-NOVAY-SKOLA-V-ZAKARINO.jpg','У новой школы в Захарьино. Май 2017г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-PRUD-U-TERKVI-4.jpg','Пруд у церкви в Захарьино. Июль 2017г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-PRUD-V-ZAKARINO-V-MAE.jpg','Пруд в Захарьино. Май 2021г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-PRUD-V-ZAKARINO-V-SENTYBRE.jpg','Пруд в Захарьино. Сентябрь 2020г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-TEATRALNAY-ULITA.jpg','Театральная улица. Сентябрь 2021г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-TEPLOE-MESTO-NA-ULITE-ZDUT.jpg','Листья на асфальте. Октябрь 2018г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-TVETENIE-ROZ-U-DOMA.jpg','Кусты розы у дома. Июнь 2020г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-VESENNIE-GAZONY.jpg','Весенние газоны. Апрель 2020г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-SPORTIVNAY-ULITA-V-SERBINKE.jpg','Спортивная улица. Июль 2021г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-VID-NA-BESEDKU-V-ZAKARINO.jpg','Вид на беседку в Захарьино. Сентябрь 2020г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-VID-NA-MILITEISKII-POSELOK-S-POLYNY.jpg','Вид на Милицейский посёлок. Июнь 2022г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-VID-NA-MOSKVU-IZ-YZNOGO-BUTOVO.jpg','Вид на Москву из Южного Бутово. Октябрь 2021г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-VYSOKAY-SOSNA-U-STANTII-BUTOVO.jpg','Высокая сосна у станции Бутово. Июль 2016г.',0,0],
[1,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/U-BUTOVO-ZAMENA-ASFALTA.jpg','Замена асфальта. Август 2021г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-BABOCKA-NA-KRASNOM-TVETKE-2.jpg','Бабочка на красном цветке 2. Сентябрь 2018г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-BABOCKA-NA-KRASNOM-TVETKE.jpg','Бабочка. Сентябрь 2018г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-DEREVO-V-PARKE-GORKOGO.jpg','Красивое дерево в Парке Горького. Июль 2016г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-EZIK-NA-DOROGE.jpg','Ёжик на дороге. Июнь 2022 г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-KRASNYI-KLEN.jpg','Красный клен. Сентябрь 2014г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-NA-FONE-SINEVY.jpg','На фоне синевы. Июль 2017г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-OSENNII-PRUD.jpg','Осенний пруд. Сентябрь 2021г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-POZELTEVSII-KLEN.jpg','Пожелтевший клен. Октябрь 2018г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-PROSTO-NEBO.jpg','Синее небо. Май 2017г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-ROSITA.jpg','Рощица. Сентябрь 2021г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-SINIE-KOLOKOLCIKI-V-ZAKARINO.jpg','Синие колокольчики.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-SOCNYE-DIKIE-YBLOCKI.jpg','Сочные яблочки. Сентябрь 2014г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-STARINNYI-POEZD-NA-STANTII.jpg','Старый поезд в Михнево. Сентябрь 2019г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-TIGR-V-PARKE-GORKOGO.jpg','Тигр в Парке Горького. Июль 2006г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-TVETOCEK-SINENKII.jpg','Цветочек синенький. Июль 2016г.',0,0],
[2,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/PRIRODA-UTKA-V-PARKE-GORKOGO.jpg','Утки в Парке Горького. Июль 2006г.',0,0],
[4,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/BITSA-TROPA-SREDI-DUBOV-I-BEREZ.jpg','Осенние тропы. Октябрь 2018г.',0,0],
[4,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/BITSA-STARYE-DUBY-2.jpg','Старые дубы. Май 2017г.',0,0],
[4,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/BITSA-IMG_0142.jpg','Осенние тропки. Октябрь 2014г.',0,0],
[4,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/BITSA-IMG_0134.jpg','Осенняя дорожка. Октябрь 2014г.',0,0],
[4,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/BITSA-SPILENNYE-DEREVY.jpg','Спиленные деревья. Май 2017г.',0,0],
[4,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/BITSA-SNOVA-BELKA.jpg','Белка зимой. Февраль 2017г.',0,0],
[4,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/BITSA-BITSA-ZIMNYY-TROPA.jpg','Зимняя тропа. Январь 2017г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-00.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-01.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-02.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-03.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-04.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-05.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-06.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-07.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-08.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-09.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-10.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-11.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-12.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-13.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-14.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-15.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[5,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/STEREO-16.jpg','Расслабьте зрение и постарайтесь увидеть что внутри. Март 2021г.',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-041.jpg','Анимэ 1',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-036.jpg','Анимэ 2',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-024.jpg','Анимэ 3',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-017.jpg','Анимэ 4',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-033.jpg','Анимэ 5',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-021.jpg','Анимэ 6',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-016.jpg','Анимэ 7',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-013.jpg','Анимэ 8',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-009.jpg','Анимэ 9',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-005.jpg','Анимэ 10',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-012.jpg','Анимэ 11',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-008.jpg','Анимэ 12',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-004.jpg','Анимэ 13',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-029.jpg','Анимэ 14',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-019.jpg','Анимэ 15',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-015.jpg','Анимэ 16',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-026.jpg','Анимэ 17',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-018.jpg','Анимэ 18',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-014.jpg','Анимэ 19',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-011.jpg','Анимэ 20',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-007.jpg','Анимэ 21',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-003.jpg','Анимэ 22',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-010.jpg','Анимэ 23',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-006.jpg','Анимэ 24',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-002.jpg','Анимэ 25',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-001.jpg','Анимэ 26',0,0],
[6,'//raw.githubusercontent.com/egaxegax/fotosite/refs/heads/main/ERO-AN-000.jpg','Анимэ 27',0,0],
];
