name: Deploy static content to Pages

on:
  shedule:
    - cron:	'0 23 * * *' #	povarenok.ru feed updater
    - cron:	'0 22 * * *' #	finecooking.ru site update
    - cron:	'0 7 * * *'  #	prosto-linux feed
    - cron:	'0 9 * * *'  #	kino-teatr.ru updater
    - cron:	'0 12 * * *' #	youtube.com updater
    - cron:	'0 13 * * *' #	rutube.ru updater
    - cron:	'0 15 * * *' #	eadaily.com rss updater
    - cron:	'0 15 * * *' #	habr.com feed
    - cron:	'10 17 * * *' #	mk nauka updater
    - cron:	'0 0 * * *'	 #	voyeur feed
    - cron:	'0 3 * * *'  #	rambler msk
    - cron:	'0 3 * * *'  #	rambler mir
    - cron:	'0 4 * * *'  #	dzen.ru feed updater
    - cron:	'0 5 * * *'  #	championat rss
    - cron:	'30 4 * * *' #	rg rss
    - cron:	'30 5 * * *' #	yaplakal.com feed

  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: povarenok.ru feed updater
        if: github.event.schedule == '0 21 * * *'
        run: python3 posts/readsites.py povarenok
      - name: finecooking.ru site update
        if: github.event.schedule ==  '0 22 * * *'
        run: python3 posts/readsites.py finecooking
      - name: prosto-linux feed
        if: github.event.schedule == '0 7 * * *'
        run: python3 posts/readsites.py prosto_linux
      - name: kino-teatr.ru updater
        if: github.event.schedule == '0 9 * * *'
        run: python3 posts/readsites.py kino_kino kino_teatr
      # - name:	youtube.com updater
      #   if: github.event.schedule == '0 12 * * *'
      #   run: python3 posts/readyfeed.py
      - name:	rutube.ru updater
        if: github.event.schedule == '0 13 * * *'
        run: python3 posts/readrufeed.py
      - name: eadaily.com rss updater
        if: github.event.schedule == '0 15 * * *'
        run: python3 posts/readrss.py eadaily
      - name: habr.com feed
        if: github.event.schedule == '0 15 * * *'
        run: python3 posts/readsites.py habr
      - name: mk nauka updater
        if: github.event.schedule == '10 17 * * *'
        run: python3 posts/readrss.py mk
      - name: voyeur feed
        if: github.event.schedule == '0 0 * * *'
        run: python3 posts/readvhfeed.py
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
