name: Deploy static content to Pages
on:
  - cron:	'0 0 * * *'  #	povarenok.ru feed updater
  - cron:	'0 1 * * *'	 #	finecooking.ru site update
  - cron:	'0 10 * * *' #	prosto-linux feed
  - cron:	'0 12 * * *' #	kino-teatr.ru updater
  - cron:	'0 15 * * *' #	youtube.com updater
  - cron:	'0 16 * * *' #	rutube.ru updater
  - cron:	'0 18 * * *' #	eadaily.com rss updater
  - cron:	'0 18 * * *' #	habr.com feed
  - cron:	'0 20 * * *' #	mk nauka updater
  - cron:	'0 3 * * *'	 #	voyeur feed
  - cron:	'0 6 * * *'  #	rambler msk
  - cron:	'0 6 * * *'  #	rambler mir
  - cron:	'0 7 * * *'  #	dzen.ru feed updater
  - cron:	'0 8 * * *'  #	championat rss
  - cron:	'30 7 * * *' #	rg rss
  - cron:	'30 8 * * *' #	yaplakal.com feed

  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: povarenok.ru feed updater
        if: github.event.schedule == '0 21 * * *'
        run: python3 posts/readsites.py povarenok
      - name: finecooking.ru site update
        if: github.event.schedule ==  '0 22 * * *'
        run: python3 posts/readsites.py finecooking
      - name: habr.com feed
        if: github.event.schedule == '0 15 * * *'
        run: python3 posts/readsites.py habr
      - name: mk nauka updater
        if: github.event.schedule == '0 17 * * *'
        run: python3 posts/readrss.py mk
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
